### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by muhimur9049** [zackradisic/node-soundcloud-downloader#27] opened 2020-11-09 23:42 UTC
Randomly started getting this error about 30 minutes ago. Never happened before.

**Comment by zackradisic** [comment] 2020-11-10 16:07
Status code 400 can result from a wide range of problems. Can you copy+paste your code and the error log to help me identify what caused the error?

**Comment by muhimur9049** [comment] 2020-11-10 17:53
play.js - https://srcb.in/M9YWVLZmgY
playskip.js - https://srcb.in/4l0WBZoJ6Z
Error: Request failed with status code 400. 

~Update~: Seems like SoundCloud playlists are working again, but I kept getting the error last night.. Any idea why?

**Comment by muhimur9049** [comment] 2020-11-10 18:02
No idea what this is but just got it. https://sourceb.in/JQZRJoXEbX

**Comment by zackradisic** [comment] 2020-11-11 01:44
How many tracks are in the playlists you are using? Playlists with more than 55 tracks do not work (see #26), I've made a fix and I'll publish it to NPM when I get the chance.

As for the error you linked, I am not 100% certain what causes it. But this is what I know so far: it occurs when the client ID is fetched, and usually the module caches the client ID. However, if your project is setup so that you are constantly running new node programs (i.e. serverless function, jest tests), then you will fetch a client ID every time and I believe SoundCloud will rate limit you and this is the reason you get the error.

For example, if you take a look at the unit tests run in [actions](https://github.com/zackradisic/node-soundcloud-downloader/actions), the testing framework runs a new node process for each test and so the client ID is fetched 10 times which causes this error to appear occasionally. I'll have to take a closer look to confirm this.

**Comment by muhimur9049** [comment] 2020-11-11 20:01
Just tried a playlist with 68 songs and it errors. Anything below 55 is seeming to work though.

**Comment by zackradisic** [comment] 2020-11-12 04:52
Duplicate of #26

**Closed by zackradisic** 2020-11-12 04:52 UTC
